### ISSUE TITLE
Component 2: Partner detail page with relevant initiatives, projects and resources

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#172]
Reviewing component 2 deliverables.

3.3.2.14 Partners

* [x] Partners index
* [ ]  Partner detail page with relevant initiatives, projects and resources.

Links:

* http://osgeo.getinteractive.nl/partners/
* http://osgeo.getinteractive.nl/partners/ica/
* http://osgeo.getinteractive.nl/partners/qgis-org-association/

**Comment by jodygarnett** [comment]
These pages are edited by hand, while this can be done for projects and initiatives; resources change too often to maintain by hand.

**Comment by jodygarnett** [comment]
There may be overlap with https://github.com/OSGeo/osgeo/issues/95

**Comment by jodygarnett** [comment]
For reference here is the wireframe v9 accepted by the marketing committee:

<img width="853" alt="partner-wireframe" src="https://user-images.githubusercontent.com/629681/33118744-d841f288-cfc0-11e7-89ab-5749f381d7f3.png">

**Comment by MarvinGI** [comment]
Resources can already be coupled to partner under the resources tab on the following page:
http://osgeo.getinteractive.nl/wp-admin/post.php?post=1209&action=edit

I added a new field to manage the related projects.The related proejcts are shown in the side bar, example: http://osgeo.getinteractive.nl/partners/ica/

For initiatives we can't make a dynamic field because initiatives aren't a CPT.

**Comment by jodygarnett** [comment]
I am not sure what a CPT is?

**Comment by jodygarnett** [comment]
Thanks, closing issue
