### ISSUE TITLE
SAC osgeo_userid page

### ISSUE THREAD

**Issue by cvvergara** [OSGeo/osgeo#176]
See initial issue here:
https://trac.osgeo.org/osgeo/ticket/2065

We don't know where to put pages related pages

**Comment by jodygarnett** [comment]
SAC should have a committee page here: https://staging.www.osgeo.org/about/committees/

Right now it just links to the wiki since that was what was done for Drupal, would love it if a website page was made for each committee. The SAC page could have information pages such as osgeo_userid ?

I note from the above issue that https://staging.www.osgeo.org/osgeo_userid has been created. I have updated this page with call out actions and to make some of the sentences shorter to describe what works now; rather than what we would like to work in the future.

**Comment by jodygarnett** [comment]
Are their any more SAC pages? Or just the osgeo_userid one ...

**Comment by jodygarnett** [comment]
Going to close this since the page in question has been created; reopen if needed
