### ISSUE TITLE
Only OSGeo Projects should be presented on the initial landing page of Projects 

### ISSUE THREAD

**Issue by kalxas** [OSGeo/osgeo#68]
Perhaps this can be done with a filter that will be enabled by default?

**Comment by jodygarnett** [comment]
We can do that, it depends on our communication priorities.

I hope that by establishing the search order OSGeo Project > OSGeo Community that this issue will go away (because it will be a page or two before any non OSGeo content is visible, thus making it easier for the filters to behave as intended).

**Comment by svandenhaak** [comment]
Projects are now ordered by project type. The initial landing page only shows OSGeo projects.

**Comment by jodygarnett** [comment]
thanks!

**Comment by kalxas** [comment]
thank you
